version: "3.7"

services:
  server:
    build: .
    init: true
    container_name: puppet-service
    volumes:
      - type: bind
        source: ../data
        target: /maintain
    ports:
      - 3000:3000
    cap_add:
      - SYS_ADMIN
    restart: on-failure:5